apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-dev
nameSuffix: -dev
resources:
- ../../bases/demoapp
- namespace.yaml
transformers:
- labels.yaml
replicas:
- count: 1
  name: demo
images:
- name: pakbaz82/sampleaspnet
  newTag: latest
