apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demoapp-prd
nameSuffix: -prd
resources:
- ../../bases/demoapp
- namespace.yaml
transformers:
- labels.yaml
patchesStrategicMerge:
- |
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: demo
  spec:
    template:
      spec:
        containers:
          - name: demo
            resources:
              requests:
                cpu: 150m
                memory: 150Mi
replicas:
- count: 3
  name: demo
images:
- name: pakbaz82/sampleaspnet
  newTag: latest
