apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-prd
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: demo-prd
    namespace: demo-prd
  - kind: Deployment
    name: redis-prd
    namespace: demo-prd
  interval: 1m0s
  path: ./infrastructure/overlays/prd
  prune: true
  sourceRef:
    kind: GitRepository
    name: demo
  timeout: 2m0s

