apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demoapp-dev
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: demoapp-dev
    namespace: demoapp-dev
  - kind: Deployment
    name: redis-dev
    namespace: demoapp-dev
  interval: 1m0s
  path: ./infrastructure/overlays/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: demo
  timeout: 2m0s

