Flag --validation has been deprecated, this arg is no longer used, all resources are validated using server-side apply dry-run
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demoapp-prd
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: demoapp-prd
    namespace: demoapp-prd
  - kind: Deployment
    name: redis-prd
    namespace: demoapp-prd
  interval: 1m0s
  path: ./infrastructure/overlays/prd
  prune: true
  sourceRef:
    kind: GitRepository
    name: demo
  timeout: 2m0s

